name: MacOS SSH to GitHub Actions

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: macos-11.0

    env:
      # Change These If You Are Forking The Repo
      GitHubMail: "d.maxbg@gmail.com"
      GitHubName: "phucthinhbg"

    steps:
    - name: Set Git Configs & Secrets
      run: |
        git config --global user.email ${GitHubMail}
        git config --global user.name ${GitHubName}
        git config --global color.ui true
        git config --global credential.helper store
        echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
    - name: System Specs
      run: system_profiler SPHardwareDataType
    - name: SSH Keepalive
      run: |
        mkdir -p ~/.ssh
        cat << EOF > ~/.ssh/config
        Host *
            ServerAliveInterval 60
            StrictHostKeyChecking no
        Host github.com
            User git
            Port 22
            Hostname github.com
            TCPKeepAlive yes
            IdentitiesOnly yes
        EOF
    # Either use ngrok method or tmate method
    - name: Start SSH via ngrok
      continue-on-error: true
      timeout-minutes: 350
      uses: P3TERX/ssh2actions@main
      with:
        mode: ngrok
      env:
        # You can find this token here: https://dashboard.ngrok.com/auth/your-authtoken
        NGROK_TOKEN: ${{ 2EMNJOfZG8kW337aspR2GyopfTn_2VSWamc9Qi2xdB7ThsbDS }}
        # ngrok server region [us, eu, au, ap, sa, jp, in] (optional, default: us)
        NGROK_REGION: us
        # This password you will use when authorizing via SSH
        SSH_PASSWORD: ${{ passwd@1 }}
        # Send connection info to Telegram (optional)
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
